services:
  eeg-watchdog:
    container_name: eeg-watchdog-${BOT_NAME}  # Postfix with TASK_NAME
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${INPUT_DIR}:/data/input
      - ${OUTPUT_DIR}:/data/output
      - ${CONFIG_DIR}:/app/configs
      - ${AUTOCLEAN_DIR}:/autoclean_pipeline
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker-in-Docker
    environment:
      - TZ=UTC
      - TASK_NAME=${TASK_NAME}  # Pass task name into container
      - MAX_WORKERS=${MAX_WORKERS:-3}  # Define here instead of command
      - HOST_CONFIG_PATH=${CONFIG_DIR}
    command: 
      - "--dir"
      - "/data/input"
      - "--extensions"
      - "edf"
      - "set"
      - "vhdr"
      - "bdf"
      - "cnt"
      - "--script"
      - "/app/autoclean_wrapper.sh"
      - "--task"
      - "${TASK_NAME}"
      - "--config"
      - "/app/configs/autoclean_config.yaml"
      - "--output"
      - "/data/output"
      - "--work_dir"
      - "/autoclean_pipeline"
      - "--max-workers"
      - "${MAX_WORKERS:-3}"
    restart: unless-stopped
    privileged: true  # Required for Docker-in-Docker functionality
