version: '3.8'

services:
  eeg-watchdog-aud-assr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./config:/app/configs
      - /mnt/srv2/eeg_dependencies/autoclean_pipeline/:/autoclean_pipeline
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker-in-Docker
    environment:
      - TZ=UTC
    command: 
      - "--dir"
      - "/data/input"
      - "--extensions"
      - "edf"
      - "set"
      - "vhdr"
      - "bdf"
      - "cnt"
      - "--script"
      - "/app/autoclean_wrapper.sh"
      - "--task"
      - "MouseXdatAssr"
      - "--config"
      - "/app/configs/autoclean_config.yaml"
      - "--output"
      - "/data/output"
      - "--work_dir"
      - "/autoclean_pipeline"
      - "--max-workers"
      - "3"  # Set the maximum number of concurrent processes
    restart: unless-stopped
    privileged: true  # Required for Docker-in-Docker functionality
